spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: rootpass
    url: jdbc:mysql://localhost:3306/triangle?serverTimezone=UTC&characterEncoding=UTF-8
    sql-script-encoding: UTF-8
  profiles:
    include:
      oauth
  # swagger
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # ddl-auto : create -> Entity에 맞게 자동으로 테이블 및 필드 생성
  # show-sql : true -> 해당하는 query를 보여줌 (JPA N + 1 문제 확인용)
  jpa:
    database: mysql   # 추가 해준 부분
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect # 추가 해준 부분
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  #  http:
  #    encoding:
  #      charset: UTF-8
  #      force: true
  #      force-request: true
  #      force-response: true

  ## page 인덱스를 1부터 시작하게 만듬
  data:
    web:
      pageable:
        one-indexed-parameters: true
  # sql:
  #   init:
  #     mode: ALWAYS
  #     continue-on-error: true
  #     schema-locations: classpath*:JUSTUDY_INIT_DATABASE.sql
  #     data-locations: classpath*:JUSTUDY_INIT_DATABASE.sql

logging:
  level:
    org.hibernate.sql: debug
    org.hibernate.type: trace

vue:
  loginUrl: "localhost:8081/login"


#  utf-8 encoding 한글 깨짐 방지용
server:
  servlet:
    encoding:
      charset: UTF-8
      force: true

